### ISSUE TITLE
Improve on "specmacro.txt" for web site

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/usaxs-bluesky#587] opened 2023-02-10 01:25 UTC
Our web site has "specmacro.txt" link which shows what usaxs.mac file content looks like. This is actually really useful for staff. 
BlueSky function run_my_command_file actually places list of collection commands there, so it is useful. 
When we run in BlueSky other functions (Linkam etc.) which collect data, this document does not get updated. It would be really cool, if in this case we put in the linked text file the function itself which is being run. I am now staring at user collecting linkam run and I have no idea what he is running. I would have to log into the control computer and even then, it will be challenge.
Alternative, at least put there name of function with parameters and python file where the function is, so I have a chance to figure this out.

**Comment by prjemian** [comment] 2023-02-27 18:56
I believe this is a duplicate of #462.  @jilavsky, do you agree?

**Comment by jilavsky** [comment] 2023-02-27 20:19
yes

**Closed** 2023-02-27 20:20 UTC
Labels: duplicate, enhancement
